export const FETCH_CATEGORYS_REQUEST = " FETCH_CATEGORYS_REQUEST ";
export const FETCH_CATEGORYS_SUCCESS = " FETCH_CATEGORYS_SUCCESS ";
export const FETCH_CATEGORYS_FAILURE = " FETCH_CATEGORYS_FAILURE ";
